### ISSUE TITLE
接口测试：POST /forum/posts/remarks

### ISSUE THREAD

**Issue by SeinoNana** [EyesCMS/zhishe-cms#37]
![image](https://user-images.githubusercontent.com/50039165/80797768-48915380-8bd5-11ea-897c-886a8df48cbe.png)
![image](https://user-images.githubusercontent.com/50039165/80797840-72e31100-8bd5-11ea-9f2c-d9a9e0a15764.png)

评论发表后无法显示在评论列表中，确认一下此接口是否可用

**Comment by xjliang** [comment]
### 发表评论
![image](https://user-images.githubusercontent.com/46876506/80911952-41e91480-8d6c-11ea-8600-ca6710c32650.png)

### 查看评论列表
![image](https://user-images.githubusercontent.com/46876506/80911976-6e9d2c00-8d6c-11ea-9311-33dfe3293c0d.png)

### 我这边是可以用的
