### ISSUE TITLE
修改接口：3.14

### ISSUE THREAD

**Issue by SeinoNana** [EyesCMS/zhishe-cms#59]
3.14的返回格式由对象改成数组，不需要url1等作为前缀

**Comment by wjh674** [comment]
![522 1](https://user-images.githubusercontent.com/60882829/82579457-6b090200-9bc0-11ea-9cbd-a7690e267144.png)
![522 2](https://user-images.githubusercontent.com/60882829/82579519-83791c80-9bc0-11ea-8cc6-f73095784200.png)

将返回值改为数组，测试成功。
