### ISSUE TITLE
热门活动推荐列表

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms#81]
需要的字段如下：
1. 活动 id
2. 活动图片

需要根据活动热度推荐 top K 活动
/activities/recommended

**Comment by kylin773** [comment]
这个是新增接口吗，如何确定活动热度？

**Comment by xjliang** [comment]
是新增接口，可以按照点赞人数、发布时间排序

**Comment by xjliang** [comment]
是新增接口，可以按照点赞人数、发布时间排序

**Comment by kylin773** [comment]
活动好像没有点赞人数把，只有活动帖才有点赞人数，活动贴的数据库字段没有映射到详细的哪个活动。根据活动帖热度推荐活动帖可以吗

**Comment by xjliang** [comment]
可以吧，应该直接添加活动帖就可以了

**Comment by kylin773** [comment]
已解决，详见接口文档6.9
