### ISSUE TITLE
接口3.2 社团列表新增role字段

### ISSUE THREAD

**Issue by is-lyx** [EyesCMS/zhishe-cms#88]
新增role字段返回当前用户为社员还是社长
[
  {
    "id": 1,
    "name": "篮球社",
    "chiefName": "微微笑",
    "type": "运动",
    "state":"1",
    "avatarUrl": "http://xx/xxxx.png",
    "joinState": "未加入",
    "role":"member"（或chief）←新增
  }
]

**Comment by wjh674** [comment]
已实现

**Comment by wjh674** [comment]
[此处为commit记录](https://github.com/EyesCMS/zhishe-cms/commit/a07245272f069ef7ee322e71a50deca0039ca97c)
