### ISSUE TITLE
接口3.4 查看某个社团详情新增字段role和joinState

### ISSUE THREAD

**Issue by is-lyx** [EyesCMS/zhishe-cms#89]
Status: 200 OK

{
  "id": 2,
  "name": "篮球社",
  "chiefName": "微微笑",
  "avatarUrl": "http://xx/xxxx.png",
  "slogan": "XX社是一个非常非常厉害的社团",
  "type": "运动",
  "memberCount": 500,
  "qqGroup": "312512512"
  “role”: "chief", ←新增
  "joinState": "已加入" ←新增
}

**Comment by wjh674** [comment]
已实现

**Comment by wjh674** [comment]
[此处为commit记录](https://github.com/EyesCMS/zhishe-cms/commit/a07245272f069ef7ee322e71a50deca0039ca97c)，这个和另一个issue一起做的，所以commit记录一样
