### ISSUE TITLE
验证密保接口

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms#96]
![image](https://user-images.githubusercontent.com/46876506/83254739-d87cea00-a1e1-11ea-90a7-da27187d9216.png)

**Comment by xjliang** [comment]
![image](https://user-images.githubusercontent.com/46876506/83255152-7ec8ef80-a1e2-11ea-9485-aa00246cb0c9.png)
![image](https://user-images.githubusercontent.com/46876506/83255171-88525780-a1e2-11ea-94ec-9a4ac90b8946.png)

这个 bean 不能复用

**Comment by kylin773** [comment]
已解决
